In [3]:
import pandas as pd

In [26]:
data = pd.read_csv("data/kumpula-summer-2024.txt")

*File was missing, created myself but column don't exactly match*

#### Question 3.1
How would you read the file kumpula-summer-2024.txt in once again selecting only the YEARMODA and TEMP1 columns? Try reading the file into a new variable called temp_data and only selecting two columns. The new variable temp_data should have 92 rows and 2 columns.

In [11]:
temp_data = pd.read_csv(
    "data/kumpula-summer-2024.txt",usecols=["YEARMODA", "AVG"]
)
temp_data.head()

   YEARMODA   AVG
0  20240602  20.8
1  20240603  20.8
2  20240604  20.2
3  20240605  18.6
4  20240606  16.1

#### Question 3.2
How would you print out the number of columns in our DataFrame?

In [19]:
len(data.columns)

4

#### Question 3.3
It doesn’t make much sense to print out descriptive statistics for the dates contained in the YEARMODA column. See if you can print out the descriptive statistics again, but only for columns TEMP1, TEMP2, MAX, and MIN.

In [21]:
data[['MIN', 'MAX', 'AVG']].describe()

             MIN        MAX        AVG
count  92.000000  92.000000  92.000000
mean   14.418478  22.870652  18.361957
std     2.547006   2.476329   2.327515
min     7.700000  16.100000  12.800000
25%    12.750000  21.500000  17.150000
50%    14.650000  23.000000  18.500000
75%    16.500000  24.700000  19.900000
max    20.000000  28.000000  23.300000

#### Question 3.5
Calculate the mean temperature for the last seven days of August 2024. Do the selection using the row index values.

In [33]:
data.shape
data.loc[92-7:92, ['AVG']].mean()

AVG    17.557143
dtype: float64

#### Question 3.6
Calculate the mean temperature for the last seven days of August 2024 again. This time you should select the rows based on a condition for the YEARMODA column.

In [36]:
data['AVG'].loc[data['YEARMODA'] > 20240826]

     MAX   MIN  YEARMODA   AVG
86  21.5  15.3  20240827  17.6
87  22.0  14.1  20240828  17.5
88  22.5  14.2  20240829  18.3
89  25.1  15.9  20240830  21.4
90  23.7  13.7  20240831  16.1
91  18.9  12.0  20240901  15.0